from tkinter import *
root=Tk()
lb=Label(root,text="Login Form")
lb.grid(row=0,column=1)
l=Label(root,text="Mail")
l2=Label(root,text="Password")
txt1=Entry()
txt2=Entry()
l.grid(row=1,column=0,stick="E")
txt1.grid(row=1,column=1)
l2.grid(row=2,column=0)
txt2.grid(row=2,column=1)
check=Checkbutton(root,text="Remember Password")
check.grid(columnspan=2)
root.mainloop()