print(ord("a"))
print(ord("z"))
print(ord("A"))
print(ord("Z"))
print(ord("a"))
print(ord("e"))
print(ord("i"))
print(ord("o"))
print(ord("u"))
print(ord("A"))
print(ord("E"))
print(ord("I"))
print(ord("O"))
print(ord("U"))
print(ord("0"))
print(ord("1"))
print(ord(" "))
